database:
  host: cybersafeacademy.cdpt1yldzkan.sa-east-1.rds.amazonaws.com
  user: cybersafe
  password: NHQSeWGhxxMBdNxDQPQk
  name: cybersafe
  port: 5432
  sslmode: require

application:
  name: CyberSafe Academy
  issuer: cybersafe

docs:
  host: ec2-15-228-243-181.sa-east-1.compute.amazonaws.com
  basePath: /api
  port: 8080

jwt:
  secretKey: FATmSgjlxd2Q3U8WZMzIIN49uHCQ9JIW
  subject: userCredentials

notification:
  user: "cybersafeacad@gmail.com"
  password: "rmqzhuirbnlravbc"

frontend:
  host: ec2-18-230-115-74.sa-east-1.compute.amazonaws.com
  port: 80
  updatePasswordEndpoint: /update-password
  firstAccessEndpoint: /finish-signup

aws:
  region: sa-east-1
  usersBucketName: cybersafe-users
  usersbucketURL: https://cybersafe-users.s3.sa-east-1.amazonaws.com/
  usersProfilePictureFolder: profile-pictures
  coursesBucketName: cybersafe-courses
  coursesBucketURL: https://cybersafe-courses.s3.sa-east-1.amazonaws.com/
  coursesThumbnailFolder: thumbnails
