database:
  host: cybersafeacademy.cdpt1yldzkan.sa-east-1.rds.amazonaws.com
  user: cybersafe
  password: NHQSeWGhxxMBdNxDQPQk
  name: cybersafe
  port: 5432

application:
  name: CyberSafe Academy
  issuer: cybersafe

docs:
  host: c2-52-67-31-102.sa-east-1.compute.amazonaws.com
  basePath: /api
  port: 8080

jwt:
  secretKey: FATmSgjlxd2Q3U8WZMzIIN49uHCQ9JIW
  subject: userCredentials

mail:
  email: cybersafeacad@gmail.com
  password: rmqzhuirbnlravbc

frontend:
  host: http://localhost
  port: 5173
  updatePasswordEndpoint: /update-password
  firstAccessEndpoint: /finish-signup
