database:
  host: loremipsulum
  user: loremipsulum
  password: loremipsulum
  name: loremipsulum
  port: loremipsulum
  sslmode: loremipsulum
  timezone: loremipsulum

application:
  name: CyberSafe Academy